### ISSUE TITLE
Graduate Admission Prediction 

### ISSUE THREAD

**Issue by HrutikaBadgeri** [SamarthTech/AI-ML-Projects#10]
I would like to work on a regression-based prediction problem set that allows us to predict the admission chances of students based on various factors like test scores etc. I want to explore different data visualization techniques and train the model using several regression-based ML models like SVR, DecisionTressRegressor, etc.

Can you assign me this under hacktoberfest?

Dataset link: https://www.kaggle.com/datasets/hrutikabadgeri/graduate-admission-predict/data

**Comment by codingniket** [comment]
No need to create a issue just make a pull request
